"""The blocking surface, and the parity check that replaces a code generator.

D-8 decided the sync API is a portal facade rather than a twin generated by `unasync`, and
the reason the decision was affordable is written into this file. A generator guarantees that
the two surfaces cannot drift; a facade has to *prove* it, and the proof is cheap because
drift is possible in arity and not in semantics -- there is one implementation of a `get`,
and `SyncSession.get` is that method with a portal in front of it.

So the parity tests below are **derived from `Session` rather than listed**. A method added to
the async API and forgotten here fails `test_every_session_method_has_a_blocking_form`; an
argument renamed on one side fails the signature comparison; a return type changed fails that
too. A hand-written list of names would be a second enumeration of the API, which is the
failure D-52 is in this repository to memorialise.

The behavioural half runs against a real `sftp-server` on a pipe, because that is where the
questions the probe left open actually live -- above all: after a sync caller `break`s out of
a `scandir`, the `__aexit__` demonstrably ran, but **is the server-side handle gone?** A
`close()` of an unknown handle answers `NO_SUCH_FILE` rather than the v3 catch-all, which
makes that a usable leak probe rather than an inference from the absence of a complaint.
"""

from __future__ import annotations

import inspect
import threading
from concurrent.futures import ThreadPoolExecutor
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

import pytest
from anyio.from_thread import start_blocking_portal

import gantry_sftp
import gantry_sftp.sync as sync_module
from gantry_sftp import (
    NoSuchFileError,
    Session,
    SessionOptions,
    StateError,
)
from gantry_sftp import (
    connect as async_connect,
)
from gantry_sftp.session import DirectoryScan
from gantry_sftp.session import open_session as async_open_session
from gantry_sftp.sync import (
    BoundPortal,
    SyncDirectoryScan,
    SyncSession,
    SyncTransport,
    connect,
    open_local_server_transport,
    open_session,
    open_ssh_transport,
)
from gantry_sftp.transport import (
    find_sftp_server,
)
from gantry_sftp.transport import (
    open_local_server_transport as async_open_local_server_transport,
)
from gantry_sftp.transport import (
    open_ssh_transport as async_open_ssh_transport,
)


def needs_real_server() -> None:
    if find_sftp_server() is None:
        pytest.skip("sftp-server not installed (ships in openssh-server)")


# --- what the facade is derived from -------------------------------------------------------


def public_members(cls: type) -> dict[str, Any]:
    """Everything a caller can reach on a class, without triggering a descriptor.

    `getattr_static` rather than `getattr`, because a `property` read on the class would give
    back the property object anyway but a `getattr` on an instance would run it.
    """
    return {
        name: inspect.getattr_static(cls, name) for name in dir(cls) if not name.startswith("_")
    }


ASYNC_MEMBERS = public_members(Session)
SYNC_MEMBERS = public_members(SyncSession)

RETURN_TRANSLATIONS = {
    "walk": ("AsyncGenerator[WalkEntry]", "Iterator[WalkEntry]"),
    "glob": ("AsyncGenerator[GlobMatch]", "Iterator[GlobMatch]"),
    "scandir": ("DirectoryScan", "SyncDirectoryScan"),
}
"""The three members whose return type legitimately changes, and what it changes to.

Every other method returns exactly what the async one returns -- awaiting is what the portal
does, so `get` is still `-> int`. These three are the shapes that could not survive the thread
boundary unchanged: two async generators, which become ordinary Python iterators, and the
directory scan, which becomes the blocking context manager of the same shape.

Named rather than skipped, and checked in both directions below, so the list cannot outlive
its reason or quietly grow a fourth entry nobody argued for.
"""


def test_the_derivation_is_not_vacuous():
    # Guards the guards: every parity test below is a loop over these, and an empty dict
    # would make all of them pass while proving nothing.
    assert len(ASYNC_MEMBERS) > 40
    assert sum(inspect.iscoroutinefunction(m) for m in ASYNC_MEMBERS.values()) > 25


def test_every_session_method_has_a_blocking_form():
    """The headline. A method added to `Session` and forgotten here shows up as a name."""
    missing = sorted(set(ASYNC_MEMBERS) - set(SYNC_MEMBERS))
    assert missing == [], f"Session methods with no blocking form: {missing}"


def test_the_facade_invents_nothing_of_its_own():
    """The other direction, which is what stops the facade becoming a second API.

    A blocking-only convenience method would have nothing to be derived from and nothing to
    keep it honest -- it is exactly the drift the generated twin was meant to prevent.
    """
    extra = sorted(set(SYNC_MEMBERS) - set(ASYNC_MEMBERS))
    assert extra == [], f"SyncSession has public members Session does not: {extra}"


@pytest.mark.parametrize(
    "name", sorted(n for n, m in ASYNC_MEMBERS.items() if isinstance(m, property))
)
def test_a_property_stays_a_property(name: str):
    """`sftp.depth` must not become `sftp.depth()` on the way across the thread.

    Properties read state that is already in memory, so none of them needs the portal -- but
    that is a reason for them to be cheap, not a reason for them to change shape.
    """
    assert isinstance(SYNC_MEMBERS[name], property), f"{name} is a property on Session but not here"


@pytest.mark.parametrize(
    "name", sorted(n for n, m in ASYNC_MEMBERS.items() if not isinstance(m, property))
)
def test_a_method_keeps_its_signature(name: str):
    """Every parameter, in order, with its annotation and its default.

    `inspect.Parameter` compares name, kind, annotation and default, and `from __future__
    import annotations` makes the annotations strings on both sides -- so this also catches a
    facade that spells a type differently from the method it is forwarding to, which is how a
    reader ends up with two different answers to the same question.
    """
    assert name in SYNC_MEMBERS, f"{name} has no blocking form at all"
    theirs = inspect.signature(ASYNC_MEMBERS[name])
    ours = inspect.signature(SYNC_MEMBERS[name])
    assert list(ours.parameters.values()) == list(theirs.parameters.values())


@pytest.mark.parametrize(
    "name", sorted(n for n, m in ASYNC_MEMBERS.items() if not isinstance(m, property))
)
def test_a_method_returns_what_the_async_one_returns(name: str):
    """Awaiting is the portal's job, so the return type is unchanged except where it cannot be."""
    assert name in SYNC_MEMBERS, f"{name} has no blocking form at all"
    theirs = inspect.signature(ASYNC_MEMBERS[name]).return_annotation
    ours = inspect.signature(SYNC_MEMBERS[name]).return_annotation
    expected_from, expected_to = RETURN_TRANSLATIONS.get(name, (theirs, theirs))
    assert theirs == expected_from, f"{name}'s async return type changed; the translation is stale"
    assert ours == expected_to


def test_the_translation_table_has_no_stale_entries():
    """A translation naming a method that no longer exists is a permission nobody needs."""
    stale = sorted(set(RETURN_TRANSLATIONS) - set(ASYNC_MEMBERS))
    assert stale == [], f"translated but no longer a Session method: {stale}"


def test_only_the_streaming_shapes_are_translated():
    """The entries are exactly the members that cannot cross the boundary unchanged.

    Derived rather than restated: an async generator or a hand-written async context manager
    has to become something else, and nothing else does.
    """
    must_translate = {
        name
        for name, member in ASYNC_MEMBERS.items()
        if not isinstance(member, property)
        and (
            inspect.isasyncgenfunction(member)
            or inspect.signature(member).return_annotation == "DirectoryScan"
        )
    }
    assert set(RETURN_TRANSLATIONS) == must_translate


# --- the entry points ----------------------------------------------------------------------


def parameters(function: Any) -> list[inspect.Parameter]:
    return list(inspect.signature(function).parameters.values())


def test_connect_takes_exactly_the_async_arguments():
    """Including `session=SessionOptions(...)`, so the tunables reach the blocking surface too."""
    assert parameters(connect) == parameters(async_connect)
    assert inspect.signature(connect).return_annotation == "Iterator[SyncSession]"


def test_open_ssh_transport_takes_exactly_the_async_arguments():
    assert parameters(open_ssh_transport) == parameters(async_open_ssh_transport)
    assert inspect.signature(open_ssh_transport).return_annotation == "Iterator[SyncTransport]"


def test_open_local_server_transport_takes_exactly_the_async_arguments():
    assert parameters(open_local_server_transport) == parameters(async_open_local_server_transport)


def test_open_session_differs_only_in_the_transport_it_accepts():
    """The one argument that has to change type, isolated so the rest cannot change with it.

    A blocking `open_session` needs the portal the transport is already running on -- that is
    the whole reason `SyncTransport` exists rather than the bare transport being handed back.
    """
    ours = {p.name: p for p in parameters(open_session)}
    theirs = {p.name: p for p in parameters(async_open_session)}
    assert set(ours) == set(theirs)
    assert ours["transport"].annotation == "SyncTransport"
    assert theirs["transport"].annotation == "Transport"
    for name in set(ours) - {"transport"}:
        assert ours[name] == theirs[name], name


@pytest.mark.parametrize(
    "name", ["connect", "open_ssh_transport", "open_local_server_transport", "open_session"]
)
def test_the_bound_form_matches_the_module_level_one(name: str):
    """The two spellings of every entry point, checked against each other.

    `BoundPortal` exists so a caller can own the loop; it must not become a second API with
    its own arguments. `self` is the only difference allowed.
    """
    bound = parameters(getattr(BoundPortal, name))
    free = parameters(getattr(sync_module, name))
    assert bound[0].name == "self"
    assert bound[1:] == free


def test_every_name_in_all_resolves():
    missing = sorted(name for name in sync_module.__all__ if not hasattr(sync_module, name))
    assert missing == [], f"in __all__ but not importable: {missing}"


def test_all_is_sorted_and_not_vacuous():
    assert list(sync_module.__all__) == sorted(sync_module.__all__)
    assert len(sync_module.__all__) >= 8


def test_the_blocking_surface_is_not_reachable_from_the_top_level():
    """A deliberate omission, stated so it is a decision rather than an oversight.

    `gantry_sftp`'s namespace is the async API. The blocking one is a separate import because
    a reader who lands on `connect` should get the one this library is built around, and
    because two names spelled `connect` in one namespace is how somebody ships the wrong one.
    """
    assert "sync" not in gantry_sftp.__all__
    assert not hasattr(gantry_sftp, "SyncSession")


# --- driving it against a real server -------------------------------------------------------


def test_a_blocking_round_trip_moves_the_bytes(tmp_path: Path):
    """The whole facade in one test: two context managers, a put, a get, and no event loop."""
    needs_real_server()
    source = tmp_path / "report.csv"
    source.write_bytes(b"id,total\n1,42\n")

    with (
        open_local_server_transport(cwd=tmp_path) as transport,
        open_session(transport) as sftp,
    ):
        assert isinstance(transport, SyncTransport)
        assert isinstance(sftp, SyncSession)
        result = sftp.put(source, str(tmp_path / "uploaded.csv").encode())
        transferred = sftp.get(str(tmp_path / "uploaded.csv").encode(), tmp_path / "back.csv")

    assert result.transferred == len(source.read_bytes())
    assert transferred == len(source.read_bytes())
    assert (tmp_path / "back.csv").read_bytes() == source.read_bytes()


def test_the_session_runs_on_a_thread_that_is_not_the_callers(tmp_path: Path):
    """The mechanism, asserted rather than assumed.

    If this ever ran the loop on the calling thread, every blocking call would be re-entrant
    and the failure would look like an unrelated deadlock much later.
    """
    needs_real_server()
    caller = threading.get_ident()
    seen: list[int] = []

    with (
        open_local_server_transport(cwd=tmp_path) as transport,
        open_session(transport) as sftp,
    ):
        _ = transport.portal.call(lambda: _record(seen))
        assert sftp.server_version == 3

    assert seen, "the portal never ran anything"
    assert seen[0] != caller


async def _record(seen: list[int]) -> None:
    seen.append(threading.get_ident())


def test_an_error_arrives_as_itself_and_flat(tmp_path: Path):
    """What the reader's shielding and the group flattening buy, across the thread boundary.

    A mechanism that re-wrapped exceptions would have undone all of it silently: an anyio task
    group wraps even a single failure, and a caller who wrote `except NoSuchFileError` around
    a blocking call would stop matching.
    """
    needs_real_server()
    with (
        open_local_server_transport(cwd=tmp_path) as transport,
        open_session(transport) as sftp,
        pytest.raises(NoSuchFileError) as error,
    ):
        sftp.stat(str(tmp_path / "definitely-not-here").encode())

    assert not isinstance(error.value, BaseExceptionGroup)
    assert error.value.code == 2


def test_breaking_out_of_a_scandir_closes_the_handle_on_the_server(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """The question the D-8 probe deliberately left open, answered against a real server.

    The probe proved the `__aexit__` reached the portal's thread and returned. That is not the
    same claim as the handle being gone -- and "no complaint appeared" is not evidence, it is
    the absence of evidence. `close()` of an unknown handle answers `NO_SUCH_FILE` rather than
    the v3 catch-all `FAILURE`, so asking the server directly is a real probe.

    The handle is captured by spying on `opendir`, which is public API, rather than by reaching
    into the scan -- `DirectoryScan` clears its handle on the way out, so by the time the block
    has ended there is nothing left there to read.
    """
    needs_real_server()
    for index in range(6):
        (tmp_path / f"part-{index}.bin").write_bytes(b"x" * (index + 1))

    with (
        open_local_server_transport(cwd=tmp_path) as transport,
        open_session(transport) as sftp,
    ):
        handles = _spying_on_opendir(monkeypatch)
        with sftp.scandir(str(tmp_path).encode()) as entries:
            for _ in entries:
                break  # the case the card calls the real failure mode

        assert len(handles) == 1, "the scan did not open exactly one directory"
        with pytest.raises(NoSuchFileError) as error:
            sftp.close(handles[0])
        assert error.value.code == 2


def test_breaking_out_of_a_walk_closes_the_handle_on_the_server(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """The same question for the async-generator shape, which fails a different way.

    `walk` chains several async generators, and only closing the outermost one closes those.
    A sync `for` that breaks drops the generator, CPython closes it, and the `finally` inside
    has to reach the portal's thread -- three places this can be swallowed, so it is probed
    rather than reasoned about.
    """
    needs_real_server()
    (tmp_path / "nested").mkdir()
    (tmp_path / "nested" / "leaf.bin").write_bytes(b"x")

    with (
        open_local_server_transport(cwd=tmp_path) as transport,
        open_session(transport) as sftp,
    ):
        handles = _spying_on_opendir(monkeypatch)
        for _ in sftp.walk(str(tmp_path).encode()):
            break

        assert handles, "the walk did not open a directory"
        for handle in handles:
            with pytest.raises(NoSuchFileError):
                sftp.close(handle)


def _spying_on_opendir(monkeypatch: pytest.MonkeyPatch) -> list[bytes]:
    """Record every directory handle the server issues, whoever asked for it.

    On `Session` rather than on the facade, because that is who `DirectoryScan` and `walk`
    call -- a spy on `SyncSession.opendir` records only the handles a *caller* opened by hand,
    which is none of the ones under test here. The handles are the server's own, so what this
    proves later is about the server's state and not about a fake's bookkeeping.
    """
    handles: list[bytes] = []
    real = Session.opendir

    async def spy(session: Session, path: bytes | str) -> bytes:
        handle = await real(session, path)
        handles.append(handle)
        return handle

    monkeypatch.setattr(Session, "opendir", spy)
    return handles


def test_a_scandir_that_was_never_entered_refuses_to_iterate(tmp_path: Path):
    """The state check comes from the object underneath rather than a second copy of it.

    Iterating a scan outside its `with` would leak the handle it holds, and the blocking form
    must refuse for the same reason and with the same message as the async one.
    """
    needs_real_server()
    with (
        open_local_server_transport(cwd=tmp_path) as transport,
        open_session(transport) as sftp,
    ):
        scan = sftp.scandir(str(tmp_path).encode())
        assert isinstance(scan, SyncDirectoryScan)
        with pytest.raises(StateError) as error:
            iter(scan)
        assert error.value.args[0] == "scandir() must be entered with `async with` before iterating"


def test_a_scandir_streams_every_entry(tmp_path: Path):
    needs_real_server()
    for index in range(5):
        (tmp_path / f"part-{index}.bin").write_bytes(b"x" * (index + 1))

    with (
        open_local_server_transport(cwd=tmp_path) as transport,
        open_session(transport) as sftp,
        sftp.scandir(str(tmp_path).encode()) as entries,
    ):
        names = sorted(entry.name for entry in entries)

    assert names == [f"part-{index}.bin" for index in range(5)]


def test_walk_and_glob_come_back_as_ordinary_iterators(tmp_path: Path):
    needs_real_server()
    (tmp_path / "nested").mkdir()
    (tmp_path / "nested" / "a.csv").write_bytes(b"a")
    (tmp_path / "nested" / "b.csv").write_bytes(b"b")
    (tmp_path / "nested" / "c.txt").write_bytes(b"c")

    with (
        open_local_server_transport(cwd=tmp_path) as transport,
        open_session(transport) as sftp,
    ):
        walked = list(sftp.walk(str(tmp_path).encode()))
        matched = sorted(match.path for match in sftp.glob(str(tmp_path / "*" / "*.csv").encode()))

    assert sorted(entry.path for entry in walked) == sorted(
        [str(tmp_path).encode(), str(tmp_path / "nested").encode()]
    )
    assert matched == [
        str(tmp_path / "nested" / "a.csv").encode(),
        str(tmp_path / "nested" / "b.csv").encode(),
    ]


def test_several_threads_share_one_session_over_one_connection(tmp_path: Path):
    """The blocking spelling of this library's headline feature, which is `except` for threads.

    "Many transfers, one connection" is a task group asynchronously. A blocking caller has no
    task group, so the question is whether a `SyncSession` survives being called from several
    threads at once -- and it does, for a reason worth stating: `portal.call` posts to the loop
    from whatever thread it is on, so the fan-out lands on the one reader that already routes
    replies by request id. Without this a blocking user has no way to overlap transfers at all.
    """
    needs_real_server()
    for index in range(8):
        (tmp_path / f"src-{index}.bin").write_bytes(b"x" * (10_000 * (index + 1)))

    with (
        open_local_server_transport(cwd=tmp_path) as transport,
        open_session(transport) as sftp,
    ):

        def fetch(index: int) -> int:
            return sftp.get(
                str(tmp_path / f"src-{index}.bin").encode(), tmp_path / f"dst-{index}.bin"
            )

        with ThreadPoolExecutor(max_workers=8) as pool:
            transferred = list(pool.map(fetch, range(8)))

    assert transferred == [10_000 * (index + 1) for index in range(8)]
    for index in range(8):
        assert (tmp_path / f"dst-{index}.bin").stat().st_size == 10_000 * (index + 1)


def test_a_progress_callback_still_reports(tmp_path: Path):
    """Callbacks cross the boundary in the other direction: our thread calls the caller's code."""
    needs_real_server()
    source = tmp_path / "big.bin"
    source.write_bytes(b"x" * 200_000)
    seen: list[tuple[int, int | None]] = []

    with (
        open_local_server_transport(cwd=tmp_path) as transport,
        open_session(transport) as sftp,
    ):
        sftp.put(
            source,
            str(tmp_path / "up.bin").encode(),
            progress=lambda done, total: seen.append((done, total)),
        )

    assert seen, "the progress callback was never called"
    assert seen[-1] == (200_000, 200_000)


def test_a_callback_that_calls_back_in_fails_loudly_rather_than_deadlocking(tmp_path: Path):
    """The hazard the portal shape creates, probed rather than asserted to be impossible.

    A `progress` callback runs on the portal's thread, and that is the one thread that cannot
    wait on the portal. anyio refuses it; the failure mode worth ruling out is the other one,
    where the call waits for a loop that is waiting for it.
    """
    needs_real_server()
    source = tmp_path / "big.bin"
    source.write_bytes(b"x" * 200_000)
    refusals: list[str] = []

    def reentrant(done: int, total: int | None) -> None:
        try:
            sftp.stat(b".")
        except RuntimeError as error:
            refusals.append(str(error))

    with (
        open_local_server_transport(cwd=tmp_path) as transport,
        open_session(transport) as sftp,
    ):
        sftp.put(source, str(tmp_path / "up.bin").encode(), progress=reentrant)

    assert refusals
    assert refusals[0] == "This method cannot be called from the event loop thread"


def test_the_legacy_publish_names_still_reach_the_session(tmp_path: Path):
    """`**legacy` is forwarded, so 0.9's deprecated spellings behave the same here.

    A facade that dropped them would make the blocking surface a place where a warning
    silently becomes a `TypeError`, which is worse than not having the surface.
    """
    needs_real_server()
    source = tmp_path / "report.csv"
    source.write_bytes(b"id,total\n1,42\n")

    with (
        open_local_server_transport(cwd=tmp_path) as transport,
        open_session(transport) as sftp,
        pytest.warns(DeprecationWarning) as warnings_raised,
    ):
        result = sftp.put(source, str(tmp_path / "plain.csv").encode(), atomic=False)

    assert result.mechanism.value == "in-place"
    assert "put(): atomic moved into the Publish object" in str(warnings_raised[0].message)


def test_the_session_refuses_calls_after_its_block_has_ended(tmp_path: Path):
    """Naming the mistake rather than the mechanism.

    Without this the same call surfaces as anyio's "This portal is not running", which tells a
    reader about a thread they never asked for instead of about the `with` block they left.
    """
    needs_real_server()
    with (
        open_local_server_transport(cwd=tmp_path) as transport,
        open_session(transport) as sftp,
    ):
        assert sftp.server_version == 3

    with pytest.raises(StateError) as error:
        sftp.listdir(str(tmp_path).encode())
    assert error.value.args[0] == "this session is closed; its `with` block has ended"

    # `scandir` is not a blocking call, so it would otherwise sail past the check and fail
    # later, inside a `with`, as anyio's complaint about a portal instead.
    with pytest.raises(StateError) as deferred:
        sftp.scandir(str(tmp_path).encode())
    assert deferred.value.args[0] == "this session is closed; its `with` block has ended"


def test_the_repr_says_which_session_and_whether_it_is_spent(tmp_path: Path):
    """A facade that hid the session it wraps would make every bug report one step longer."""
    needs_real_server()
    with (
        open_local_server_transport(cwd=tmp_path) as transport,
        open_session(transport) as sftp,
    ):
        live = repr(sftp)
        assert repr(transport).startswith("<SyncTransport over ")
        assert repr(sftp.scandir(b".")) == "<SyncDirectoryScan over <DirectoryScan b'.' unopened>>"

    assert live.startswith("<SyncSession over <Session server=openssh")
    assert repr(sftp).startswith("<SyncSession closed over <Session server=openssh")


def test_connect_forwards_its_session_options(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    """The fused entry point, driven rather than inspected.

    `open_ssh_transport` is replaced because what is under test is the composition and a real
    connection here would need a host; the session half and the portal are real.
    """
    needs_real_server()

    @asynccontextmanager
    async def fake_transport(host: str, **kwargs: object):
        async with async_open_local_server_transport(cwd=tmp_path) as transport:
            yield transport

    monkeypatch.setattr("gantry_sftp._connect.open_ssh_transport", fake_transport)

    with connect("example.invalid", user="bob", session=SessionOptions(depth=3)) as sftp:
        assert sftp.depth == 3
        assert sftp.server_version == 3


# --- owning the portal ----------------------------------------------------------------------


def test_one_portal_can_carry_several_sessions(tmp_path: Path):
    """The reason `BoundPortal` exists: a thread and a loop per connection is a real cost.

    Both sessions are live at once and both work, which is what a fan-out job needs and what
    portal-per-connection charges a thread apiece for.
    """
    needs_real_server()
    (tmp_path / "one.bin").write_bytes(b"1")
    (tmp_path / "two.bin").write_bytes(b"22")

    with start_blocking_portal() as portal:
        gantry = BoundPortal(portal)
        assert gantry.portal is portal
        with (
            gantry.open_local_server_transport(cwd=tmp_path) as first_transport,
            gantry.open_session(first_transport) as first,
            gantry.open_local_server_transport(cwd=tmp_path) as second_transport,
            gantry.open_session(second_transport) as second,
        ):
            assert first.stat(b"one.bin").size == 1
            assert second.stat(b"two.bin").size == 2
            # Still one loop, so still one thread doing the work for both.
            assert first_transport.portal is second_transport.portal


def test_a_caller_can_run_the_facade_on_trio(tmp_path: Path):
    """The other reason to own the portal, and the one that would have been a `backend=` argument.

    This library is anyio-shaped so that trio costs nothing, and a blocking surface pinned to
    asyncio would spend that for the caller. Owning the portal is the whole of the answer.
    """
    needs_real_server()
    (tmp_path / "one.bin").write_bytes(b"1")

    with start_blocking_portal(backend="trio") as portal:
        gantry = BoundPortal(portal)
        with (
            gantry.open_local_server_transport(cwd=tmp_path) as transport,
            gantry.open_session(transport) as sftp,
        ):
            assert sftp.stat(b"one.bin").size == 1
            assert sorted(entry.name for entry in sftp.listdir(b".")) == ["one.bin"]


def test_the_portal_a_caller_owns_outlives_the_session(tmp_path: Path):
    """Nothing in the facade starts or stops a portal it was handed."""
    needs_real_server()
    with start_blocking_portal() as portal:
        gantry = BoundPortal(portal)
        with (
            gantry.open_local_server_transport(cwd=tmp_path) as transport,
            gantry.open_session(transport) as sftp,
        ):
            assert sftp.server_version == 3
        # The session is spent and the portal is not: a second one opens on the same loop.
        with (
            gantry.open_local_server_transport(cwd=tmp_path) as again_transport,
            gantry.open_session(again_transport) as again,
        ):
            assert again.server_version == 3


def test_the_bound_portal_repr_names_the_portal():
    """Which portal, not just that there is one -- with several in play that is the question."""
    with start_blocking_portal() as portal:
        rendered = repr(BoundPortal(portal))
        assert rendered.startswith("<BoundPortal ")
        assert repr(portal) in rendered


# --- the objects the async layer still owns ---------------------------------------------------


def test_the_scan_wraps_the_async_one_rather_than_reimplementing_it(tmp_path: Path):
    """Stated as an identity, because the alternative is a second directory reader.

    `SyncDirectoryScan` holds a `DirectoryScan`; the batching, the dot filtering and the
    latched EOF are that object's and are tested where it lives.
    """
    needs_real_server()
    with (
        open_local_server_transport(cwd=tmp_path) as transport,
        open_session(transport) as sftp,
    ):
        scan = sftp.scandir(b".")
        assert isinstance(scan._scan, DirectoryScan)  # noqa: SLF001


def test_the_transport_hands_back_the_async_object_it_carries(tmp_path: Path):
    """`SyncTransport.transport` is the escape hatch, and it is the real transport."""
    needs_real_server()
    with open_local_server_transport(cwd=tmp_path) as transport:
        assert hasattr(transport.transport, "send")
        assert hasattr(transport.transport, "receive")
